module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
    'gh-pages': {
      options: {
        base: 'generatedCodeDocumentation' ,
        message: 'Generated by grunt gh-pages'
      } ,
      src: ['/Documentation/html/**/*']
    },
    });
    grunt.loadNpmTasks('grunt-gh-pages');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.registerTask ('deploy', ['develop', 'gh-pages']);
};